name: ChatHook
version: 1.0.0
author: archessmn
main: com.github.archessmn.ChatHook.main
api-version: 1.16

commands:
  link:
    description: For linking your minecraft account to your discord account.